#!/usr/bin/env bash
# One-shot launcher for the poker app.
#
# Usage:
#   ./start.sh                 # local stack (localhost) — web :8088
#   ./start.sh prod            # production stack (Caddy TLS) — asks for domain/IP
#   DOMAIN=poker.example.com ./start.sh prod   # non-interactive prod
#   ./start.sh down            # stop everything (data is kept)
#   ./start.sh prod --reset-db # DESTROYS the database volume, then starts fresh
#
# DigitalOcean (or any Ubuntu VM with Docker):
#   git clone <repo> && cd <repo> && ./start.sh prod
#   Point a DNS A record at the droplet IP and enter the domain when asked —
#   Caddy obtains the TLS certificate automatically.
#
# Cloudflare (proxied orange cloud):
#   ./start_prod.sh
#   # or: DOMAIN=juegapoker.online ./start.sh prod
#   Dashboard SSL/TLS mode: Full or Full (strict). WebSockets: On.
#   WEB_ORIGIN becomes https://<domain> so invite links / QR use that host.
#   Direct IP access is blocked (403) at Caddy; use the domain only.
#   See docs/deploy.md
set -euo pipefail

cd "$(dirname "$0")"

# Fixed project name so containers/volumes are stable regardless of folder name.
export COMPOSE_PROJECT_NAME=chips

MODE="local"
DOMAIN="${DOMAIN:-}"
RESET_DB=false

for arg in "$@"; do
  case "$arg" in
    local|prod|down) MODE="$arg" ;;
    --reset-db) RESET_DB=true ;;
    --domain=*) DOMAIN="${arg#--domain=}" ;;
    -h|--help)
      awk 'NR>1 && /^#/ {print substr($0,3)} NR>1 && !/^#/ {exit}' "$0"
      exit 0
      ;;
    *) echo "Unknown argument: $arg (see ./start.sh --help)" >&2; exit 1 ;;
  esac
done

# ---------- helpers ----------

log()  { printf '\033[1;32m[start]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[start]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[start]\033[0m %s\n' "$*" >&2; exit 1; }

need() { command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"; }

gen_secret() { # gen_secret <bytes>
  openssl rand -hex "$1"
}

compose_dev() {
  docker compose "$@"
}

compose_prod() {
  if [[ -f .env.production ]]; then
    docker compose -f docker-compose.prod.yml --env-file .env.production "$@"
  else
    # Interpolation-only dummies so `down` works before the env file exists.
    POSTGRES_PASSWORD=dummy JWT_SECRET=dummy \
      docker compose -f docker-compose.prod.yml "$@"
  fi
}

down_all() {
  # Plain string, not array: empty arrays break under `set -u` on macOS bash 3.2.
  local vol_flag=""
  if $RESET_DB; then
    warn "--reset-db: the database volume WILL BE DESTROYED."
    vol_flag="-v"
  fi
  log "Stopping any running stack..."
  # shellcheck disable=SC2086
  compose_dev down --remove-orphans $vol_flag 2>/dev/null || true
  # shellcheck disable=SC2086
  compose_prod down --remove-orphans $vol_flag 2>/dev/null || true
}

pg_volume_exists() {
  docker volume inspect "${COMPOSE_PROJECT_NAME}_postgres_data" >/dev/null 2>&1
}

lan_ip() {
  if command -v ipconfig >/dev/null 2>&1; then
    ipconfig getifaddr en0 2>/dev/null || true
  elif command -v hostname >/dev/null 2>&1; then
    hostname -I 2>/dev/null | awk '{print $1}' || true
  fi
}

wait_for_health() { # wait_for_health <compose_fn> <label>
  local fn="$1" label="$2" i
  log "Waiting for API health ($label)..."
  for i in $(seq 1 60); do
    if "$fn" exec -T api node -e \
      "fetch('http://127.0.0.1:3001/health').then(r=>r.text().then(t=>{console.log(t);process.exit(r.ok?0:1)})).catch(()=>process.exit(1))" \
      2>/dev/null; then
      log "API is healthy."
      return 0
    fi
    sleep 3
  done
  warn "API did not become healthy in time. Recent logs:"
  "$fn" logs --tail 40 api || true
  warn "If Postgres logs show 'password authentication failed', the database"
  warn "volume was created with a different password. Fresh start (DESTROYS data):"
  warn "  ./start.sh $MODE --reset-db"
  exit 1
}

# ---------- env generation ----------

ensure_env_local() {
  if [[ -f .env ]]; then
    log "Reusing existing .env"
    return
  fi
  local pg_pass jwt
  if pg_volume_exists; then
    # The existing volume was almost certainly initialized with the defaults.
    warn "Existing database volume found — keeping default local DB credentials."
    pg_pass="poker"
  else
    pg_pass="$(gen_secret 16)"
  fi
  jwt="$(gen_secret 32)"
  log "Generating .env (local)"
  cat > .env <<EOF
# Generated by start.sh $(date -u +%Y-%m-%dT%H:%M:%SZ) — local stack

POSTGRES_USER=poker
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_DB=poker
POSTGRES_PORT=5433
DATABASE_URL=postgresql://poker:${pg_pass}@localhost:5433/poker

REDIS_PORT=6380
REDIS_URL=redis://localhost:6380

API_PORT=3001
JWT_SECRET=${jwt}
WEB_ORIGIN=http://localhost:8088

WEB_PORT=8088
# Empty in docker: browser uses same-origin /ws via nginx proxy
VITE_WS_URL=
EOF
  chmod 600 .env
}

ensure_env_prod() {
  if [[ -f .env.production ]]; then
    log "Reusing existing .env.production"
    if [[ -n "$DOMAIN" ]] && ! rg -q "SITE_ADDRESS=.*${DOMAIN}" .env.production 2>/dev/null \
      && ! grep -q "SITE_ADDRESS=.*${DOMAIN}" .env.production 2>/dev/null; then
      warn "DOMAIN='$DOMAIN' differs from .env.production — delete the file to regenerate."
    fi
    return
  fi

  if pg_volume_exists && ! $RESET_DB; then
    warn "A database volume exists but .env.production does not."
    warn "The generated DB password will NOT match the existing volume."
    read -r -p "Destroy the existing database volume and start fresh? [y/N] " answer
    case "$answer" in
      y|Y|yes|YES)
        RESET_DB=true
        docker volume rm "${COMPOSE_PROJECT_NAME}_postgres_data" >/dev/null 2>&1 || true
        ;;
      *) die "Aborted. Re-run with --reset-db, or restore your previous .env.production." ;;
    esac
  fi

  if [[ -z "$DOMAIN" ]]; then
    echo
    echo "Public address for this deployment:"
    echo "  - a domain (e.g. juegapoker.online)  -> HTTPS via Caddy/Let's Encrypt"
    echo "  - a public IP (e.g. 164.90.10.20)    -> plain HTTP (no cert for bare IPs)"
    echo "  - empty                              -> localhost (self-signed HTTPS)"
    echo "  Behind Cloudflare: use the domain; set SSL mode to Full (or Full strict)."
    read -r -p "Domain or IP (empty = localhost): " DOMAIN
  fi

  local site origin
  if [[ -z "$DOMAIN" || "$DOMAIN" == "localhost" ]]; then
    site="localhost"
    origin="https://localhost"
  elif [[ "$DOMAIN" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    site="http://${DOMAIN}"
    origin="http://${DOMAIN}"
  else
    # Strip accidental scheme/trailing slash from DOMAIN=
    DOMAIN="${DOMAIN#https://}"
    DOMAIN="${DOMAIN#http://}"
    DOMAIN="${DOMAIN%/}"
    site="$DOMAIN"
    origin="https://${DOMAIN}"
  fi

  log "Generating .env.production (SITE_ADDRESS=${site})"
  cat > .env.production <<EOF
# Generated by start.sh $(date -u +%Y-%m-%dT%H:%M:%SZ) — production stack

POSTGRES_USER=poker
POSTGRES_PASSWORD=$(gen_secret 24)
POSTGRES_DB=poker

JWT_SECRET=$(gen_secret 32)

WEB_ORIGIN=${origin}
SITE_ADDRESS=${site}

HTTP_PORT=80
HTTPS_PORT=443
EOF
  chmod 600 .env.production
}

# ---------- main ----------

need docker
need openssl
docker info >/dev/null 2>&1 || die "Docker daemon is not running."
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required (docker compose)."

down_all

if [[ "$MODE" == "down" ]]; then
  log "Stack stopped."
  exit 0
fi

if [[ "$MODE" == "local" ]]; then
  ensure_env_local
  log "Building and starting local stack..."
  compose_dev up --build -d
  wait_for_health compose_dev "local"

  ip="$(lan_ip)"
  echo
  log "Ready!"
  echo "  Web:    http://localhost:8088"
  echo "  Health: http://localhost:3001/health"
  [[ -n "$ip" ]] && echo "  Phones on the same Wi-Fi: http://${ip}:8088"
  echo
  echo "  Logs:  docker compose logs -f"
  echo "  Stop:  ./start.sh down"
else
  ensure_env_prod
  log "Building and starting production stack..."
  compose_prod up --build -d
  wait_for_health compose_prod "prod"

  site="$(rg -o '^SITE_ADDRESS=(.*)' -r '$1' .env.production 2>/dev/null \
    || grep '^SITE_ADDRESS=' .env.production | head -1 | cut -d= -f2)"
  echo
  log "Ready!"
  case "$site" in
    http://*) echo "  Web: ${site}" ;;
    localhost) echo "  Web: https://localhost  (self-signed cert — accept the browser warning)" ;;
    *) echo "  Web: https://${site}" ;;
  esac
  echo
  echo "  Logs:    docker compose -f docker-compose.prod.yml --env-file .env.production logs -f"
  echo "  Stop:    ./start_prod.sh down   (or ./start.sh down)"
  echo "  Backup:  ./scripts/backup-postgres.sh"
  echo "  Note:    direct IP access returns 403 — use the domain only"
fi
